### ISSUE TITLE
Memory usage display incorrect

### ISSUE THREAD

**Issue by gkze** [ManoMarks/docker-swarm-visualizer#22] opened 2016-09-01 21:14 UTC
Running on a 1.12 cluster, seeing incorrect output:

<img width="1286" alt="screen shot 2016-09-01 at 2 13 01 pm" src="https://cloud.githubusercontent.com/assets/3131232/18184513/48206036-704e-11e6-9a7b-0e6507c26055.png">

These machines are almost maxed out, should be showing ~1-2GB free

**Comment by woyorus** [comment] 2016-09-24 00:51
The problem is that Docker reports total memory for nodes, not free memory. Workaround is changing labels to make it more clear — #26

**Comment by ManoMarks** [comment] 2016-10-28 00:58
Fixed in #26

**Closed by ManoMarks** 2016-10-28 00:58 UTC
